### ISSUE TITLE
What version of PARI-GP used ?

### ISSUE THREAD

**Issue by Hurd8x** [cysecud/ecc_weak_keys#1]
Good day.

Then I try run codes I get errors on  ALL scrypts.I think latest version of PARI not work with your scrypts ?

Thank you.

**Comment by enh11** [comment]
Hi there, 

I've already run codes and everything works OK to me.I'm running GP/PARI CALCULATOR Version 2.15.4.
Please, find attached a copy/paste of my gp session, just to show you that it works. I copied codes from Curve383187.gp  file on the repository. 

You can also try to run codes as follows:
1. Download from the repository the .gp file you are interested in,  (example: Curve383187.gp);
2. Run Parigp;
3. Type the following command:  \r /path/of/your/file/Curve383187.gp and press enter;
computation should starts.


If you get errors please let me know. I can try to understand what's wrong.
Regards.
Enrico

[gp_session.txt](https://github.com/user-attachments/files/17932641/gp_session.txt)

**Comment by Hurd8x** [comment]
> Hi there,
> 
> I've already run codes and everything works OK to me.I'm running GP/PARI CALCULATOR Version 2.15.4. Please, find attached a copy/paste of my gp session, just to show you that it works. I copied codes from Curve383187.gp file on the repository. 
> 
> You can also try to run codes as follows:
> 
> 1. Download from the repository the .gp file you are interested in,  (example: Curve383187.gp);
> 2. Run Parigp;
> 3. Type the following command:  \r /path/of/your/file/Curve383187.gp and press enter;
>    computation should starts.
> 
> If you get errors please let me know. I can try to understand what's wrong. Regards. Enrico
> 
> [gp_session.txt](https://github.com/user-attachments/files/17932641/gp_session.txt)

Thank you for reply.

I try this file

https://github.com/cysecud/ecc_weak_keys/blob/master/gp_code/alg.gp


output:


userland@localhost:~/13/ecc_weak_keys/gp_code$ gp -q alg.gp
Type key_pairs_gen() to generate your private key and public key
Type test_key(you_public_key,bound_for_the_test) to test your key
? key_pairs_gen
()->d=div32[1];zd=115481771728459905245102424859900657047113141323743738905491223467302634970004;sk=lift(Mod(zd,p)^random(d));pk=ellmul(E,P,sk);print("Your private and public keys have been generated!\nType sk to visualize you secret key and pk to visualize the public key.")
? pk
pk
? sk
sk
?

what I do wrong ? I try recive public key and private key,but unsuccessful.


ps My version of gp is different, maybe I have no result because of it.


Thank you very mach.

**Comment by enh11** [comment]
Ok now I understand. Instead of running alg.gp you have to run secp256k1.gp. Then, alg.gp will run automatically (it is run by the last line of the code in secp256k1.gp). 
I suggest you to download the folder gp_code, the run parigp and type

\r /your/path/gp_code/secp256k1.gp

Now you can start your test.

**Comment by Hurd8x** [comment]
> Ok now I understand. Instead of running alg.gp you have to run secp256k1.gp. Then, alg.gp will run automatically (it is run by the last line of the code in secp256k1.gp). I suggest you to download the folder gp_code, the run parigp and type
> 
> \r /your/path/gp_code/secp256k1.gp
> 
> Now you can start your test.

secp256k1.gp not contain string about algo.gp


seco256k1.gp:


print("This is elliptic curve secp256k1");
print("y^2=x^3-7");
q = 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f;
print("defined over the finite field Fq where \n q = " q);
a = Mod(0x0000000000000000000000000000000000000000000000000000000000000000, q);
b = Mod(0x0000000000000000000000000000000000000000000000000000000000000007, q);
E = ellinit([a, b],q);
P = [Mod(55066263022277343669578718895168534326250603453777594175500187360389116729240,q),Mod(32670510020758816978083085130507043184471273380659243275938904335757337482424,q)];
p=115792089237316195423570985008687907852837564279074904382605163141518161494337;
z=Mod(7, p);
div32 = [18051648];
div64 = [18051648, 6871154804262114368, 10306732206393171552, 15996907278672735013];
div128 = [1938057310625759192294976, 3154049060501396119538597952, 9782462315356940942943205974373470912, 41427743093894159295282972951876913728, 192897928780944679218661342807176879546, 225103679124018650938499972290963477356, 257197238374592905624881790409569172728, 300138238832024867917999963054617969808];
div160 = [6172733720990229734997162969829660145472, 338624364920977752681389262317185522840540224];

**Comment by enh11** [comment]
Oh! I forgot to git push long time ago. 
I have just pushed now. Download it again. It should work.
Thank you!

**Comment by Hurd8x** [comment]
> Oh! I forgot to git push long time ago. I have just pushed now. Download it again. It should work. Thank you!

Oh, yes, mister, now all work:


userland@localhost:~/13/13/ecc_weak_keys/gp_code$
gp -q secp256k1.gp
This is elliptic curve secp256k1
y^2=x^3-7
defined over the finite field Fq where
 q = 115792089237316195423570985008687907853269984665640564039457584007908834671663
Type key_pairs_gen() to generate your private key and public key
Type test_key(you_public_key,bound_for_the_test) to test your key
? key_pairs_gen
()->d=div32[1];zd=115481771728459905245102424859900657047113141323743738905491223467302634970004;sk=lift(Mod(zd,p)^random(d));pk=ellmul(E,P,sk);print("Your private and public keys have been generated!\nType sk to visualize you secret key and pk to visualize the public key.")
? pk
pk
? sk
sk
? key_pairs_gen()
Your private and public keys have been generated!
Type sk to visualize you secret key and pk to visualize the public key.
? pk
[Mod(15082517359000147371703545448537779779783703943154367759348226164272700643883, 115792089237316195423570985008687907853269984665640564039457584007908834671663), Mod(42497839521293684573184706198506912554809336488225568870647095025902454102392, 115792089237316195423570985008687907853269984665640564039457584007908834671663)]
? sk
44348743552956812846079094070520967561910055000250760028817952285884041702560
?



thank you very mach,
have a good day.
