### ISSUE TITLE
Error, then try test_key

### ISSUE THREAD

**Issue by Hurd8x** [cysecud/ecc_weak_keys#3]
Good day.

Haw to resolve this problem ?

Thank you.

problem:

`? key_pairs_gen()
Your private and public keys have been generated!
Type sk to visualize you secret key and pk to visualize the public key.
? pk
[Mod(15082517359000147371703545448537779779783703943154367759348226164272700643883, 115792089237316195423570985008687907853269984665640564039457584007908834671663), Mod(42497839521293684573184706198506912554809336488225568870647095025902454102392, 115792089237316195423570985008687907853269984665640564039457584007908834671663)]
? test_key((15082517359000147371703545448537779779783703943154367759348226164272700643883, 115792089237316195423570985008687907853269984665640564039457584007908834671663), Mod(42497839521293684573184706198506912554809336488225568870647095025902454102392, 115792089237316195423570985008687907853269984665640564039457584007908834671663,13)
  ***   syntax error, unexpected ')', expecting
  ***   )-> or ',': ...4039457584007908834671663
  ***   ),Mod(424978395212936
  ***   ^---------------------
? test_key((15082517359000147371703545448537779779783703943154367759348226164272700643883, 115792089237316195423570985008687907853269984665640564039457584007908834671663), Mod(42497839521293684573184706198506912554809336488225568870647095025902454102392, 115792089237316195423570985008687907853269984665640564039457584007908834671663),13
  ***   syntax error, unexpected ')', expecting
  ***   )-> or ',': ...4039457584007908834671663
  ***   ),Mod(424978395212936
  ***   ^---------------------
? test_key((15082517359000147371703545448537779779783703943154367759348226164272700643883, 115792089237316195423570985008687907853269984665640564039457584007908834671663), Mod(42497839521293684573184706198506912554809336488225568870647095025902454102392, 115792089237316195423570985008687907853269984665640564039457584007908834671663),13)
  ***   syntax error, unexpected ')', expecting
  ***   )-> or ',': ...4039457584007908834671663
  ***   ),Mod(424978395212936
  ***   ^---------------------
? test_key(((15082517359000147371703545448537779779783703943154367759348226164272700643883, 115792089237316195423570985008687907853269984665640564039457584007908834671663), Mod(42497839521293684573184706198506912554809336488225568870647095025902454102392, 115792089237316195423570985008687907853269984665640564039457584007908834671663),13)
  ***   syntax error, unexpected ')', expecting
  ***   )-> or ',': ...4039457584007908834671663
  ***   ),Mod(424978395212936
  ***   ^---------------------
?`

**Comment by enh11** [comment]
You are missing a Mod.
your public key is 
pk = [Mod(150825173590...43883, 11579208923731619542...1663), Mod(4249783952129368457...02392, 11579208923731...671663)]
If you want to refer to this value and test for it,  just use the name you gave to it, i.e., pk!
Thus, to run a test type:

 test_key(pk,32)

Note: you are also trying a test with a bound of 13, which is not allowed in my codes. Allowed bound are 32,64,128,160. 

I've just added some if condition in the code, so that you can be aware if you are giving a wrong bound as input. Download the code again from the repository.

**Comment by Hurd8x** [comment]
> You are missing a Mod. your public key is pk = [Mod(150825173590...43883, 11579208923731619542...1663), Mod(4249783952129368457...02392, 11579208923731...671663)] If you want to refer to this value and test for it, just use the name you gave to it, i.e., pk! Thus, to run a test type:
> 
> test_key(pk,32)
> 
> Note: you are also trying a test with a bound of 13, which is not allowed in my codes. Allowed bound are 32,64,128,160.
> 
> I've just added some if condition in the code, so that you can be aware if you are giving a wrong bound as input. Download the code again from the repository.

Thank you very mach.
