### ISSUE TITLE
Error is the same in another PC with 128gb mrmory

### ISSUE THREAD

**Issue by Hurd8x** [cysecud/ecc_weak_keys#8]
![20241129_210129](https://github.com/user-attachments/assets/e9765cec-34cb-44b4-a275-25ad27b261a1)
![20241129_210111](https://github.com/user-attachments/assets/a7426c8f-191a-4afc-91a9-955b3a7fe736)

Problem is the same, oh.

Pleeease,fix this problem.Please.

**Comment by enh11** [comment]
On my station works perfectly. I made some modification and git pushed. 
Download gp_code zip from https://github.com/cysecud/ecc_weak_keys or use command line 
gh repo clone cysecud/ecc_weak_keys.
Then run gp
type 
\r /your/path/gp_code/secp256k1.gp and script should start.
Enter the key you want to test, give her name. Example:

pk=[Mod(15082517359000147371703545448537779779783703943154367759348226164272700643883, 115792089237316195423570985008687907853269984665640564039457584007908834671663), Mod(42497839521293684573184706198506912554809336488225568870647095025902454102392, 115792089237316195423570985008687907853269984665640564039457584007908834671663)]

Then, run the function test_key:

test_key(pk,32)

You will get as output the corresponding secret key 

44348743552956812846079094070520967561910055000250760028817952285884041702560
![Screenshot from 2024-12-02 09-34-46](https://github.com/user-attachments/assets/b65207e9-b16e-423c-b536-3f5ea9d06cdb)

**Comment by Hurd8x** [comment]
error:

key_pairs_gen()
Your private and public keys have been generated!
Type sk to visualize you secret key and pk to visualize the public key.
? pk
[Mod(15082517359000147371703545448537779779783703943154367759348226164272700643883, 115792089237316195423570985008687907853269984665640564039457584007908834671663), Mod(42497839521293684573184706198506912554809336488225568870647095025902454102392, 115792089237316195423570985008687907853269984665640564039457584007908834671663)]
? sk
44348743552956812846079094070520967561910055000250760028817952285884041702560
? test_key(pk,32)
Point to be tested:
 [Mod(15082517359000147371703545448537779779783703943154367759348226164272700643883, 115792089237316195423570985008687907853269984665640564039457584007908834671663), Mod(42497839521293684573184706198506912554809336488225568870647095025902454102392, 115792089237316195423570985008687907853269984665640564039457584007908834671663)]
Divisor: 18051648
  ***   at top-level: test_key(pk,32)
  ***                 ^---------------
  ***   in function test_key:
  ***   ...ound==32,foreach(div32,d,
  ***   bsgs(public_key,d)),i
  ***   ^---------------------
  ***   in function bsgs:
  ***   ...P,lift(Mod(zd,p)^(m*i)));
  ***   foreach(bs,baby_step,
  ***   ^---------------------
  ***   not a function in function call
  ***   Break loop: type 'break' to go back to GP
  ***   prompt
break>

**Comment by Hurd8x** [comment]
break> pk=[Mod(15082517359000147371703545448537779779783703943154367759348226164272700643883, 115792089237316195423570985008687907853269984665640564039457584007908834671663), Mod(42497839521293684573184706198506912554809336488225568870647095025902454102392, 115792089237316195423570985008687907853269984665640564039457584007908834671663)]
[Mod(15082517359000147371703545448537779779783703943154367759348226164272700643883, 115792089237316195423570985008687907853269984665640564039457584007908834671663), Mod(42497839521293684573184706198506912554809336488225568870647095025902454102392, 115792089237316195423570985008687907853269984665640564039457584007908834671663)]
break> test_key(pk,32)                            Point to be tested:                                [Mod(15082517359000147371703545448537779779783703943154367759348226164272700643883, 115792089237316195423570985008687907853269984665640564039457584007908834671663), Mod(42497839521293684573184706198506912554809336488225568870647095025902454102392, 115792089237316195423570985008687907853269984665640564039457584007908834671663)]
Divisor: 18051648
  ***   at top-level: test_key(pk,32)
  ***                 ^---------------
  ***   in function test_key:
  ***   ...ound==32,foreach(div32,d,
  ***   bsgs(public_key,d)),i
  ***   ^---------------------
  ***   in function bsgs:
  ***   ...P,lift(Mod(zd,p)^(m*i)));
  ***   foreach(bs,baby_step,
  ***   ^---------------------
  ***   in function foreach: test_key(pk,32)
  ***                        ^---------------
  ***   in function test_key:
  ***   ...ound==32,foreach(div32,d,
  ***   bsgs(public_key,d)),i
  ***   ^---------------------
  ***   in function bsgs:
  ***   ...P,lift(Mod(zd,p)^(m*i)));
  ***   foreach(bs,baby_step,
  ***   ^---------------------
  ***   not a function in function call
  ***   Break loop: type 'break' to go back to GP
  ***   prompt
break[2]>

**Comment by Hurd8x** [comment]
This same error description 

https://pari.math.u-bordeaux.fr/archives/pari-users-2003/msg00006.html

**Comment by Hurd8x** [comment]
![20241202_091442](https://github.com/user-attachments/assets/76be883b-0c2d-46fa-9e1c-7b2592f5ed49)


Worked in ubuntu 22, in ubuntu 20 not work.

Thank you very mach

**Comment by threealgos** [comment]
hi man i hope you can donate ? 1NEJcwfcEm7Aax8oJNjRUnY3hEavCjNrai you for my Quantum Project here is  python.py code
[Grover-ibm.py.txt](https://github.com/user-attachments/files/18003755/Grover-ibm.py.txt) .

**Comment by enh11** [comment]
Oh nice! I actually don't know what is the problem. I'm running Ubuntu 24.04.1 and everything works.
Regards.
